global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus' # Adjust to match your Spring Boot app's metrics path
    static_configs:
      - targets: ['host.docker.internal:8080'] # Replace with the host and port of your Spring Boot app
