# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches:
      - main

env:
  REGISTRY_NAME: docker.pkg.github.com
  REGISTRY_REPO: up2code/spring-book-store
  APP_VERSION: 1.0.0

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '21'
        cache: 'maven'
    
    - name: Run test
      run: mvn test

    - name: Build with Maven
      run: mvn clean package --file pom.xml